# Generated by Django 3.1.6 on 2021-02-11 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('my_gym', '0002_usermodel_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ManyToManyField(blank=True, to='my_gym.ServiceModel')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_gym.subscriptionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='StaffInfoModel',
            new_name='StaffProfileModel',
        ),
        migrations.RenameField(
            model_name='staffprofilemodel',
            old_name='staff',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='ClientInfoModel',
        ),
    ]
