# Generated by Django 3.1.6 on 2021-02-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gym', '0003_auto_20210211_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='is_updated',
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='services',
            field=models.ManyToManyField(to='my_gym.ServiceModel'),
        ),
    ]
